name: baseflow

on:
  workflow_call:

jobs:
  build:
    name: Build, lint and test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"

      - name: Checkout private glyphs repo
        uses: actions/checkout@v4
        with:
          repository: artem-rodionov/docgen-private
          path: .docgen-private
          ssh-key: ${{ secrets.PRIVATE_DEPLOY_KEY }}

      - name: Install dependencies
        run: uv sync

      - name: Run linter
        run: uv run ruff check .

      - name: Copy files into fake
        run: |
          mkdir -p src/test/fixtures
          cp -r .docgen-private/. src/test/fixtures/

      - name: Run tests
        env:
          API_TOKEN: ${{ secrets.API_TOKEN }}
        run: uv run pytest
