name: Standart checks

on:
  pull_request:
    types: [opened, synchronize, reopened, closed]
  push:
    branches: [ master ]

jobs:
  call_lint_workflow:
    uses: ./.github/workflows/baseflow.yml
    secrets: inherit
